### PR TITLE
20.04 - Focal Fossa

### PR DESCRIPTION
**Pull request by igor-cali**
Focal Fossa release date.
Code refreshed.

### CODE REVIEW

**Comment by leinardi** [comment]
Hi Igor, thanks a lot for the PR, unfortunately I can't release a new version immediately because there is a UI issue when showing the widgets:
image
This should not be related to your changes, I suspect it happens only on newer version of Android.
Anyway I would like to fix this before releasing but I'm not sure when I'll find the time to do it.

If you want to have a look at this, feel free to do it, just rebase your fork on the upstream master because I pushed some big changes today and soon I'll try to migrate the project to Android X.

**Comment by igor-cali** [comment]
Thanks. I did not understand what is the issue with UI. Can you explain, so I can check if I can help?

**Comment by leinardi** [comment]
Sure, it should look like this:
image
You can see more screenshots here: https://play.google.com/store/apps/details?id=com.leinardi.ubuntucountdownwidget&hl=en_US

Basically the side of the image are cut.

**Comment by igor-cali** [comment]
So the issue is on corners. Same look on my device (version from Play Store).

I take advantage, would you be ok to publish the app in the F-Droid Foss Store?

**Comment by leinardi** [comment]
I don't think the problem is with the corners, I think the image is cropped on the side because the image is a square and the widget shape is a rectangle. Regarding F-Droid we can talk, about it, when the issue is fixed, I don't see why not.

**Pull request merged**
